# Stage 1
FROM node as prod-build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
EXPOSE 3000
RUN npm run build

# Stage 2
FROM nginx
COPY --from=prod-build /app/build /usr/share/nginx/html

